# git
alias gs="git status"
alias gst="git stash"
alias gb="git branch"
alias gbd="git branch -D"
alias gco="git checkout"
alias gcod="git checkout develop"
alias gpd="git pull origin develop"
alias ga="git add -A"
alias gc="ga && git commit -m"
alias gpl="git pull"
alias gps="git push"
alias gch="git checkout HEAD"
alias gl="git log"
# apps
alias vimrc="vim ~/.vimrc"
alias pro="vim ~/.bash_profile"
alias reset="source ~/.bash_profile"
alias finder="open -a 'Finder'"
alias subl="open -a 'Sublime Text'"
alias vs="open -a 'Visual Studio Code'"
alias atm="open -a Atom"
alias code="cd ~/Documents/code/"
alias chrome="open -a 'Google Chrome'"
alias safari="open -a 'Safari"
alias stp="open -a 'Safari Technology Preview'"
alias ff="open -a Firefox"
alias ffd="open -a FirefoxDeveloperEdition"
alias server="python -m SimpleHTTPServer 3000"
# system
alias flush="sudo dscacheutil -flushcache;sudo killall -HUP mDNSResponder;"
alias lsa="ls -a"
