# VS Code extensions
extensions=(
Orta.vscode-jest
Perkovec.emoji
PeterJausovec.vscode-docker
QassimFarid.ejs-language-support
RobinMalfait.prettier-eslint-vscode
TwentyChung.jsx
TwentyChung.jsx-snippets
abusaidm.html-snippets
adamwalzer.scss-lint
alefragnani.Bookmarks
alissoncfr.vdf
andischerer.theme-atom-one-dark
anseki.vscode-color
AravindKumar.gherkin-indent
avli.clojure
bale.theme-darkplusplus
bradgashler.htmltagwrap
castwide.solargraph
christian-kohler.npm-intellisense
CoenraadS.bracket-pair-colorizer
cssho.vscode-svgviewer
dbaeumer.vscode-eslint
donjayamanne.githistory
donjayamanne.jquerysnippets
DotJoshJohnson.xml
dzannotti.vscode-babel-coloring
eg2.tslint
eg2.vscode-npm-script
esbenp.prettier-vscode
fabiospampinato.vscode-browser-refresh
formulahendry.terminal
gerane.Theme-BatmanLight
gerane.Theme-Daguiheso
gerane.Theme-EggplantParm
gerane.Theme-ToyMachine
hirofumii.rubyblue-theme
hnw.vscode-auto-open-markdown-preview
hollowtree.vue-snippets
johnpapa.Angular2
mohsen1.prettify-json
ms-python.python
ms-vscode.sublime-keybindings
ms-vscode.Go
ms-vscode.sublime-keybindings
ms-vscode.Theme-MarkdownKit
ms-vscode.vs-keybindings
ms-vsliveshare.vsliveshare
msjsdiag.debugger-for-chrome
oderwat.indent-rainbow
onemore.simplescript
oysun.vuehelper
pthorsson.vscode-jsp
qinjia.view-in-browser
rebornix.Ruby
redhat.java
shinnn.stylelint
slevesque.shader
steoates.autoimport
vscjava.vscode-java-debug
vscjava.vscode-java-pack
vscjava.vscode-java-test
vscjava.vscode-maven
xabikos.JavaScriptSnippets
xabikos.ReactSnippets
xaver.theme-tubbs
Zignd.html-css-class-completion
)
for i in "${extensions[@]}"
do
	code --install-extension $i
done
